Gem::Specification.new do |spec|
  spec.name = "javaclass"
  spec.version = "0.2.1"
  spec.summary = "javaclass is a java class file parser for ruby."
  spec.author = "Masaya Yamauchi"
  spec.email = "y-masaya@red.hot.co.jp"
  spec.homepage = "http://github.com/unageanu/javaclass/tree/master"
  spec.files = [
    "test/java_class",
    "test/java_class/com",
    "test/java_class/com/example",
    "test/java_class/com/example/TestClass1$1.class",
    "test/java_class/com/example/TestClass1$Hoo.class",
    "test/java_class/com/example/TestClass1$Var.class",
    "test/java_class/com/example/TestClass1.class",
    "test/java_class/com/example/TestClass2$1.class",
    "test/java_class/com/example/TestClass2$Hoo.class",
    "test/java_class/com/example/TestClass2.class",
    "test/java_src",
    "test/java_src/com",
    "test/java_src/com/example",
    "test/java_src/com/example/TestClass1.java",
    "test/java_src/com/example/TestClass2.java",
    "test/test_access_flag.rb",
    "test/test_attribute.rb",
    "test/test_class.rb",
    "test/test_constant.rb",
    "test/test_member.rb",
    "test/test_util.rb",
    "lib/javaclass",
    "lib/javaclass/accessflag.rb",
    "lib/javaclass/attribute.rb",
    "lib/javaclass/base.rb",
    "lib/javaclass/class.rb",
    "lib/javaclass/constant.rb",
    "lib/javaclass/member.rb",
    "lib/javaclass/reader.rb",
    "lib/javaclass/ziputils.rb",
    "lib/javaclass.rb",
    "sample/create_assert.rb",
    "sample/dependency.rb",
    "sample/find.rb",
    "sample/java_class",
    "sample/java_class/com",
    "sample/java_class/com/example",
    "sample/java_class/com/example/annotation",
    "sample/java_class/com/example/annotation/Annotated.class",
    "sample/java_class/com/example/annotation/AnnotatedMethod$A.class",
    "sample/java_class/com/example/annotation/AnnotatedMethod$B.class",
    "sample/java_class/com/example/annotation/AnnotatedMethod$C.class",
    "sample/java_class/com/example/annotation/AnnotatedMethod.class",
    "sample/java_class/com/example/annotation/ClassAnnotationA.class",
    "sample/java_class/com/example/annotation/HasDefaultValue.class",
    "sample/java_class/com/example/annotation/RuntimeAnnotationA.class",
    "sample/java_class/com/example/annotation/RuntimeAnnotationB.class",
    "sample/java_class/com/example/annotation/RuntimeAnnotationC.class",
    "sample/java_class/com/example/annotation/SourceAnnotationA.class",
    "sample/java_class/com/example/Constants.class",
    "sample/java_class/com/example/Deprecated.class",
    "sample/java_class/com/example/InnerClass$1.class",
    "sample/java_class/com/example/InnerClass$BasicInnerClass.class",
    "sample/java_class/com/example/InnerClass$StaticInnerClass$InnerInnerClass.class",
    "sample/java_class/com/example/InnerClass$StaticInnerClass$StaticInnerInnerClass.class",
    "sample/java_class/com/example/InnerClass$StaticInnerClass.class",
    "sample/java_class/com/example/InnerClass.class",
    "sample/java_class/com/example/InnerClassImpl$1.class",
    "sample/java_class/com/example/InnerClassImpl$1MethodInnerClass.class",
    "sample/java_class/com/example/InnerClassImpl$2.class",
    "sample/java_class/com/example/InnerClassImpl$BasicInnerClass2.class",
    "sample/java_class/com/example/InnerClassImpl$StaticInnerClass2.class",
    "sample/java_class/com/example/InnerClassImpl.class",
    "sample/java_class/com/example/Kitten.class",
    "sample/java_class/com/example/ThrowsException.class",
    "sample/java_class/com/example/types",
    "sample/java_class/com/example/types/TypeVariables.class",
    "sample/java_class/HelloWorld.class",
    "sample/java_src",
    "sample/java_src/com",
    "sample/java_src/com/example",
    "sample/java_src/com/example/annotation",
    "sample/java_src/com/example/annotation/Annotated.java",
    "sample/java_src/com/example/annotation/AnnotatedMethod.java",
    "sample/java_src/com/example/annotation/ClassAnnotationA.java",
    "sample/java_src/com/example/annotation/HasDefaultValue.java",
    "sample/java_src/com/example/annotation/RuntimeAnnotationA.java",
    "sample/java_src/com/example/annotation/RuntimeAnnotationB.java",
    "sample/java_src/com/example/annotation/RuntimeAnnotationC.java",
    "sample/java_src/com/example/annotation/SourceAnnotationA.java",
    "sample/java_src/com/example/Constants.java",
    "sample/java_src/com/example/Deprecated.java",
    "sample/java_src/com/example/InnerClass.java",
    "sample/java_src/com/example/InnerClassImpl.java",
    "sample/java_src/com/example/Kitten.java",
    "sample/java_src/com/example/ThrowsException.java",
    "sample/java_src/com/example/types",
    "sample/java_src/com/example/types/TypeVariables.java",
    "sample/java_src/HelloWorld.java",
    "sample/sample.jar",
    "sample/sample.rb",
    "sample/type_hierarchy.rb",
    "README",
    "ChangeLog"]
  spec.test_files = [
    "test/java_class",
    "test/java_class/com",
    "test/java_class/com/example",
    "test/java_class/com/example/TestClass1$1.class",
    "test/java_class/com/example/TestClass1$Hoo.class",
    "test/java_class/com/example/TestClass1$Var.class",
    "test/java_class/com/example/TestClass1.class",
    "test/java_class/com/example/TestClass2$1.class",
    "test/java_class/com/example/TestClass2$Hoo.class",
    "test/java_class/com/example/TestClass2.class",
    "test/java_src",
    "test/java_src/com",
    "test/java_src/com/example",
    "test/java_src/com/example/TestClass1.java",
    "test/java_src/com/example/TestClass2.java",
    "test/test_access_flag.rb",
    "test/test_attribute.rb",
    "test/test_class.rb",
    "test/test_constant.rb",
    "test/test_member.rb",
    "test/test_util.rb"]
  spec.has_rdoc = true
  spec.rdoc_options << "--main" << "README"
  spec.extra_rdoc_files = ["README"]
  spec.add_dependency('rubyzip', '>= 0.9.1')
end
